from __future__ import annotations
from dataclasses import dataclass
from typing import Any, Optional, Protocol, Dict


@dataclass
class BatchContext:
    epoch: int
    batch_idx: int
    batch_size: Optional[int] = None
    extra: Optional[Dict[str, Any]] = None


class TrainingObserver(Protocol):
    def on_train_start(self, ctx: Dict[str, Any] | None = None) -> None: ...
    def on_epoch_start(self, epoch: int) -> None: ...
    def on_batch_start(self, bc: BatchContext) -> None: ...
    def on_after_forward(self, bc: BatchContext, outputs: Any) -> None: ...
    def on_after_loss(self, bc: BatchContext, loss: Any, outputs: Any, targets: Any) -> None: ...
    def on_after_backward(self, bc: BatchContext) -> None: ...
    def on_after_step(self, bc: BatchContext) -> None: ...
    def on_batch_end(self, bc: BatchContext) -> None: ...
    def on_epoch_end(self, epoch: int) -> None: ...
    def on_train_end(self, ctx: Dict[str, Any] | None = None) -> None: ...
